import { addDays, formatISO, setHours, startOfDay, subDays } from "date-fns";
import type { DemoState } from "@/domain/types";

const today = startOfDay(new Date());
const at = (dayOffset: number, hour: number) =>
  formatISO(setHours(addDays(today, dayOffset), hour));
const day = (dayOffset: number) =>
  formatISO(addDays(today, dayOffset), { representation: "date" });

export const demoState: DemoState = {
  currentUser: {
    id: "usr-admin",
    name: "Alex Kim",
    email: "admin@example.org",
    role: "admin",
    status: "active",
    department: "Live Stream",
    timezone: "Asia/Kolkata",
    phone: "+91 90000 00000",
    whatsapp: "+91 90000 00000",
    notificationPreferences: { email: true, push: false },
  },
  profiles: [
    {
      id: "usr-admin",
      name: "Alex Kim",
      email: "admin@example.org",
      role: "admin",
      status: "active",
      department: "Live Stream",
      timezone: "Asia/Kolkata",
      notificationPreferences: { email: true, push: false },
    },
    {
      id: "usr-morgan",
      name: "Morgan Lee",
      email: "morgan@example.org",
      role: "member",
      status: "active",
      department: "Live Stream",
      timezone: "Asia/Kolkata",
      notificationPreferences: { email: true, push: true },
    },
    {
      id: "usr-jordan",
      name: "Jordan Patel",
      email: "jordan@example.org",
      role: "member",
      status: "active",
      department: "Live Stream",
      timezone: "Asia/Kolkata",
      notificationPreferences: { email: true, push: true },
    },
    {
      id: "usr-taylor",
      name: "Taylor Chen",
      email: "taylor@example.org",
      role: "member",
      status: "invited",
      department: "Live Stream",
      timezone: "Asia/Kolkata",
      notificationPreferences: { email: true, push: false },
    },
  ],
  shifts: [
    {
      id: "shift-1",
      startsAt: at(0, 6),
      endsAt: at(0, 12),
      period: "Morning",
      location: "Drishti Studio",
      assignees: [
        { id: "usr-morgan", name: "Morgan Lee" },
        { id: "usr-admin", name: "Alex Kim" },
      ],
      updatedAt: new Date().toISOString(),
    },
    {
      id: "shift-2",
      startsAt: at(0, 16),
      endsAt: at(0, 22),
      period: "Evening",
      location: "Drishti Studio",
      assignees: [
        { id: "usr-jordan", name: "Jordan Patel" },
        { id: "usr-taylor", name: "Taylor Chen" },
      ],
      updatedAt: new Date().toISOString(),
    },
    {
      id: "shift-3",
      startsAt: at(1, 6),
      endsAt: at(1, 12),
      period: "Morning",
      location: "Drishti Studio",
      assignees: [
        { id: "usr-morgan", name: "Morgan Lee" },
        { id: "usr-admin", name: "Alex Kim" },
      ],
      updatedAt: new Date().toISOString(),
    },
    {
      id: "shift-4",
      startsAt: at(1, 16),
      endsAt: at(1, 22),
      period: "Evening",
      location: "Drishti Studio",
      assignees: [{ id: "usr-jordan", name: "Jordan Patel" }],
      updatedAt: new Date().toISOString(),
    },
  ],
  inventory: [
    {
      id: "inv-1",
      name: "Sony PXW-Z190 Camera",
      type: "Camera",
      location: "Drishti Store",
      available: 3,
      total: 4,
      serialNumber: "CAM-Z190",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "inv-2",
      name: "Magewell HDMI Capture",
      type: "Capture Card",
      location: "Drishti Store",
      available: 6,
      total: 8,
      serialNumber: "MW-HDMI",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "inv-3",
      name: "Sennheiser Wireless Kit",
      type: "Audio",
      location: "Audio Rack",
      available: 2,
      total: 3,
      serialNumber: "EW-DP",
      updatedAt: new Date().toISOString(),
    },
    {
      id: "inv-4",
      name: "SDI Cable 30m",
      type: "Cable",
      location: "Cable Bay",
      available: 9,
      total: 12,
      updatedAt: new Date().toISOString(),
    },
  ],
  requests: [
    {
      id: "REQ-1042",
      title: "GLP IE 7 Step",
      requester: {
        id: "usr-morgan",
        name: "Morgan Lee",
        department: "Live Stream",
      },
      fromDate: day(1),
      toDate: day(4),
      purpose: "Camera and audio coverage",
      status: "submitted",
      items: [
        {
          id: "req-item-1",
          inventoryItemId: "inv-1",
          name: "Sony PXW-Z190 Camera",
          quantity: 1,
          returnedQuantity: 0,
        },
        {
          id: "req-item-2",
          inventoryItemId: "inv-3",
          name: "Sennheiser Wireless Kit",
          quantity: 1,
          returnedQuantity: 0,
        },
      ],
      createdAt: subDays(new Date(), 1).toISOString(),
      updatedAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: "REQ-1038",
      title: "Video publication setup",
      requester: {
        id: "usr-jordan",
        name: "Jordan Patel",
        department: "Live Stream",
      },
      fromDate: day(-4),
      toDate: day(-1),
      purpose: "Temporary editing station",
      status: "issued",
      items: [
        {
          id: "req-item-3",
          inventoryItemId: "inv-2",
          name: "Magewell HDMI Capture",
          quantity: 1,
          returnedQuantity: 0,
        },
      ],
      createdAt: subDays(new Date(), 8).toISOString(),
      updatedAt: subDays(new Date(), 4).toISOString(),
      isOverdue: true,
    },
    {
      id: "REQ-1032",
      title: "Studio cable replacement",
      requester: {
        id: "usr-admin",
        name: "Alex Kim",
        department: "Live Stream",
      },
      fromDate: day(-8),
      toDate: day(-6),
      purpose: "Replace faulty long cable",
      status: "returned",
      items: [
        {
          id: "req-item-4",
          inventoryItemId: "inv-4",
          name: "SDI Cable 30m",
          quantity: 2,
          returnedQuantity: 2,
          returnCondition: "good",
        },
      ],
      createdAt: subDays(new Date(), 12).toISOString(),
      updatedAt: subDays(new Date(), 6).toISOString(),
    },
  ],
  tickets: [
    {
      id: "TKT-218",
      title: "Studio 9 audio drops",
      description: "Audio stops unexpectedly after several minutes.",
      location: "Studio 9",
      status: "pending",
      priority: "high",
      reporter: { id: "usr-jordan", name: "Jordan Patel" },
      assignee: { id: "usr-morgan", name: "Morgan Lee" },
      comments: [],
      createdAt: subDays(new Date(), 2).toISOString(),
      updatedAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: "TKT-221",
      title: "PCR desktop system check",
      description: "Run the last-system checklist before the next program.",
      location: "DT14",
      status: "unassigned",
      priority: "medium",
      reporter: { id: "usr-admin", name: "Alex Kim" },
      comments: [],
      createdAt: subDays(new Date(), 1).toISOString(),
      updatedAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: "TKT-210",
      title: "Remove unused pipes",
      description: "Coordinate with the network team.",
      location: "Outside Drishti",
      status: "closed",
      priority: "low",
      reporter: { id: "usr-jordan", name: "Jordan Patel" },
      assignee: { id: "usr-taylor", name: "Taylor Chen" },
      comments: [],
      createdAt: subDays(new Date(), 9).toISOString(),
      updatedAt: subDays(new Date(), 3).toISOString(),
    },
  ],
  notifications: [
    {
      id: "notif-1",
      title: "Inventory request awaiting approval",
      message: "REQ-1042 is ready for review.",
      href: "/app?section=inventory",
      read: false,
      createdAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: "notif-2",
      title: "Ticket assigned",
      message: "TKT-218 was assigned to Morgan Lee.",
      href: "/app?section=tickets",
      read: false,
      createdAt: subDays(new Date(), 1).toISOString(),
    },
    {
      id: "notif-3",
      title: "Tomorrow's roster",
      message: "Morning shift has two volunteers.",
      href: "/app?section=roster",
      read: true,
      createdAt: subDays(new Date(), 2).toISOString(),
    },
  ],
  links: [
    {
      id: "link-1",
      name: "Drishti Calendar",
      url: "https://calendar.google.com/",
      order: 1,
    },
    {
      id: "link-2",
      name: "Step 7 Config",
      url: "https://docs.google.com/spreadsheets/",
      order: 2,
    },
    {
      id: "link-3",
      name: "Monitoring Gallery",
      url: "https://live-miracles.github.io/gallery",
      order: 3,
    },
    {
      id: "link-4",
      name: "Delayed YouTube",
      url: "https://live-miracles.github.io/delayed-yt",
      order: 4,
    },
  ],
  homeContent: {
    supportMessage:
      "Namaskaram! Please stay a-Live. Keep studios clean, sign the entry book and do not move installed equipment.",
    guidelines:
      "No food in studios. Leave bags outside. Switch on the green light when your session starts. Report equipment changes through a ticket.",
    whatsappUrl: "https://chat.whatsapp.com/",
    tutorialUrl: "https://www.youtube.com/",
  },
};
