const QUOTES = [
    'The life of Rama shows the immense Possibility of being Human – the capability to rise above All Challenges.',
    'Devotion is when your involvement with life is so absolute that you yourself do not matter anymore.',
    'Water is life-making material. Saving water resources is Saving Life.',
    'When you were a child, someone had to work hard to make you miserable. Today, someone has to work hard to make you happy. Time to understand that the source of Human experience is within oneself.',
    'The more exclusive you make yourself in thought and emotion, the more excluded from Life you become.',
    'If you want success and joy in whatever you do, the most important thing is Clarity of Perception.',
    'This is the nature of your Mind: if you try to avoid certain thoughts, only those will occur.',
    'When you spend time in the forest, you realize you are just one more Life. It is a huge spiritual step to feel for Life around you the way you feel for yourself.',
    'The Mind, which is the greatest Miracle, has become a misery-manufacturing machine for too many people.',
    'Do not save your Joy for later. When you are joyful, your whole life is a celebration.',
    'Whatever your life situation, there is no reason to be miserable. You came with nothing, so you are always on the profit side.',
    'When it comes to Joy, Love, and the Exuberance of Life, you are the Source of it.',
    'The best way to be receptive to Grace is to become less of yourself.',
    'Once you see the limitations in which you exist, a natural longing to Go Beyond them arises – and that is your biggest fortune.',
    'Those who are absolutely sure of everything have put their Intelligence in cold storage.',
    'Living an Exuberant Life is only possible when you are able to dance upon the uncertainties of life.',
    'What is a friend? A friend is another confused human being like you. If you can be with each other sincerely, that is when real friendship happens.',
    'Relationships are an opportunity to create a Union that paves the way to a greater possibility.',
    'Whether it is song, dance, or work – if you throw yourself into it with total Abandon, your life will become wonderful.',
    'If who you are is clearly established within yourself, what people say will not matter.',
    'Love is the longing to include someone as a part of you – to expand the boundaries of who you are beyond yourself.',
    'We may not always be able to change the physical situations around us. But no one can stop us from changing the way we Experience them.',
    'When you become silent within yourself, you will perceive Life in a way you cannot imagine – in utmost profoundness.',
    'Wherever you are, whatever you are exposed to, pick up the best from every situation. Then, Life is Learning.',
    'Life is a limited amount of time. You can make it mediocre, terrible, or fantastic. This is all the choice you have.',
    'Do not waste your time and Life on things that do not matter. What truly matters to you, commit to it one hundred percent – today, not tomorrow.',
    'Mastery of anything does not come without absolute Devotion.',
    'Meditation is not a conquest or achievement – it is a homecoming.',
    'What fragrance is to a flower, Love is to a human being.',
    'No matter what you did yesterday, in this moment you can be a wonderful human being if you want to.',
    'You are only given the raw material for your Life. What you make out of it is up to you.',
    'There is always one more step to climb. That is why Life is worth living.',
    'If you maintain Exuberance of energy, freshness of mind, and a loving heart, every day is a new adventure.',
    'There is no cause greater than Life.',
    'To make your surroundings pleasant, you need cooperation. To make your body, mind, and energy pleasant is one hundred percent your business.',
    'If your Intelligence was working for you, you would not make yourself miserable.',
    'Love means being willing to Nurture another Life beyond opinions and prejudice.',
    'In a world where information is available to everyone, Education must become Inspiration, not an accumulation of knowledge.',
    'Whatever you are doing in life, you chose it in some way. Do it as the most important thing – it shall become your Meditation.',
    'Realizing the Full Potential of Life is more important than how long you live.',
    'Taking care of the environment is not an obligation – our environment is our life.',
    'If you are truly Committed to what you care for, the whole world will support you.',
    'You are not suffering Life. You are suffering your memory and imagination.',
    'Success is when situations do not decide who you are – you decide how the situation should be.',
    'Yoga means Union. Yoga also means ultimate empowerment.',
    'Breath and heartbeat are vital for the body. Being Meditative is vital for the Human Being.',
    'From today onward, do not drag your feet. Dance your way through Life.',
    'Education needs Inspiration, not just information.',
    'Life is not in its goal. Life is in its process – in how you Experience it within yourself right now.',
    'Love does not give you sense. It just gives you the right intent.',
    'When new situations arise – even ones you do not like – Embrace them.',
    'When you are Joyful, you are not in conflict with anyone, and you do the most wonderful things.',
    'Life is not about What you do. It is all about How you do it.',
    'Tomorrow never comes. That is the beauty of life: you only need to learn to handle today.',
    'How profoundly you are involved – that is how profound the experience of life is.',
    'In Stillness, there is no time.',
    'Whatever you have – your Love, your Joy, your Skills – show them now.',
    'You cannot transform the world without transforming the Individual.',
    'If you care for people around you, you must make yourself into a person they enjoy being with.',
    'Karma has nothing to do with good and bad. It is only about cause and effect.',
    'If you pay Attention to the Life that you are, it will blossom within you.',
    'Believing means assuming something you do not truly know. Seeking means recognizing that you do not know.',
    'The secret of life is to see everything with a Non-Serious eye, but to be Absolutely Involved.',
    'Abundance is not about your clothes, home, or car. True Abundance is about how joyful, loving, and ecstatic you are.',
    'Human intelligence holds the greatest potential in the known universe, if only we use it Consciously.',
    'If you want to know the Joy of activity, the first and foremost thing is to give yourself to activity with total Abandon.',
    'Their own thoughts, emotions, and needs keep most people busy for a lifetime. To be above this is Yoga.',
];

export function getRandomQuote(): string {
    return QUOTES[Math.floor(Math.random() * QUOTES.length)];
}
